<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/pandas/blob/main/20optional_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
from google.colab import files
uploaded=files.upload()

Saving car_price_prediction_with_missing.csv to car_price_prediction_with_missing.csv

In [11]:
filepath="/content/car_price_prediction_with_missing.csv"
df=pd.read_csv("car_price_prediction_with_missing.csv")

In [12]:
df

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1.0,Tesla,2016.0,2.3,Petrol,Manual,114832.0,New,26613.92,Model X
1,2.0,BMW,2018.0,4.4,Electric,Manual,143190.0,Used,14679.61,5 Series
2,3.0,Audi,2013.0,4.5,Electric,Manual,181601.0,New,44402.61,A4
3,4.0,Tesla,2011.0,4.1,Diesel,Automatic,68682.0,New,86374.33,Model Y
4,5.0,Ford,2009.0,2.6,Diesel,Manual,223009.0,Like New,73577.10,Mustang
...,...,...,...,...,...,...,...,...,...,...
2495,2496.0,Audi,2020.0,2.4,Petrol,Automatic,22650.0,Like New,61384.10,Q5
2496,2497.0,Audi,2001.0,5.7,Hybrid,Manual,77701.0,Like New,24710.35,A3
2497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2498,2499.0,Audi,2002.0,4.5,Diesel,Manual,229164.0,Like New,46085.67,Q5
2499,2500.0,Toyota,2005.0,4.6,Diesel,Automatic,80978.0,Used,16594.14,RAV4

In [13]:
print("Independent:")
X=df.drop('Mileage',axis=1)
X.head()

Independent:

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Condition,Price,Model
0,1.0,Tesla,2016.0,2.3,Petrol,Manual,New,26613.92,Model X
1,2.0,BMW,2018.0,4.4,Electric,Manual,Used,14679.61,5 Series
2,3.0,Audi,2013.0,4.5,Electric,Manual,New,44402.61,A4
3,4.0,Tesla,2011.0,4.1,Diesel,Automatic,New,86374.33,Model Y
4,5.0,Ford,2009.0,2.6,Diesel,Manual,Like New,73577.10,Mustang

In [14]:
print("Dependent:")
Y=df['Mileage']
Y.head()

Dependent:

0    114832.0
1    143190.0
2    181601.0
3     68682.0
4    223009.0
Name: Mileage, dtype: float64

In [15]:
print("Shape of X:",X.shape)
print("Shape of Y:",Y.shape)

Shape of X: (2500, 9)
Shape of Y: (2500,)

In [42]:
categorical=X.select_dtypes(include=['object']).columns
print("Categorical columns:",categorical)
X=pd.get_dummies(X,columns=categorical,dtype=int)
X.head()

Categorical columns: Index(['Brand', 'Fuel Type', 'Transmission', 'Condition', 'Model'], dtype='object')

,Car ID,Year,Engine Size,Price,Brand_Audi,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Mercedes,Brand_Tesla,...,Model_Model S,Model_Model X,Model_Model Y,Model_Mustang,Model_Prius,Model_Q5,Model_Q7,Model_RAV4,Model_X3,Model_X5
0,1.0,0.633654,-0.830523,26613.92,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
1,2.0,0.920232,0.640711,14679.61,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3.0,0.203788,0.710770,44402.61,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4.0,-0.082789,0.430535,86374.33,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,5.0,-0.369366,-0.620347,73577.10,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [43]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ["Year", "Engine Size","Price"]

X[num_cols] = scaler.fit_transform(X[num_cols])

print(X.head())

   Car ID      Year  Engine Size     Price  Brand_Audi  Brand_BMW  Brand_Ford  \
0     1.0  0.633654    -0.830523 -0.951025           0          0           0
1     2.0  0.920232     0.640711 -1.389362           0          1           0
2     3.0  0.203788     0.710770 -0.297662           1          0           0
3     4.0 -0.082789     0.430535  1.243921           0          0           0
4     5.0 -0.369366    -0.620347  0.773891           0          0           1

   Brand_Honda  Brand_Mercedes  Brand_Tesla  ...  Model_Model S  \
0            0               0            1  ...              0
1            0               0            0  ...              0
2            0               0            0  ...              0
3            0               0            1  ...              0
4            0               0            0  ...              0

   Model_Model X  Model_Model Y  Model_Mustang  Model_Prius  Model_Q5  \
0              1              0              0            0         0
1              0              0              0            0         0
2              0              0              0            0         0
3              0              1              0            0         0
4              0              0              1            0         0

   Model_Q7  Model_RAV4  Model_X3  Model_X5
0         0           0         0         0
1         0           0         0         0
2         0           0         0         0
3         0           0         0         0
4         0           0         0         0

[5 rows x 48 columns]

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(
    X,Y,test_size=0.33,random_state=42)
print("X_train Shape :", X_train.shape)
print("X_test Shape  :", X_test.shape)
print("y_train Shape :", Y_train.shape)
print("y_test Shape  :", Y_test.shape)

X_train Shape : (1675, 48)
X_test Shape  : (825, 48)
y_train Shape : (1675,)
y_test Shape  : (825,)

In [60]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, Y_train)
print("model intercept:",model.intercept_)
print("\nmodel coefficients:",model.coef_)

model intercept: 153256.25978357217

model coefficients: [-2.73800996e+00  1.95563652e+03 -1.05154466e+03 -1.68156437e+03
  5.05356611e+03  1.95798543e+03  1.74694516e+03 -5.70576002e+02
 -7.71896023e+03  1.24253475e+03 -1.71149522e+03 -9.82191365e+02
 -6.07880892e+03  5.21512110e+03  1.84587919e+03  3.05984663e+03
 -3.05984663e+03  4.26373826e+03 -2.61505091e+03 -1.64868735e+03
 -1.65389783e+04  8.66530675e+03  8.75762167e+03 -1.58941431e+04
 -2.14062832e+04 -7.18329500e+03  1.83767532e+04  5.67834270e+03
 -5.25764362e+03 -5.28244846e+03  6.76090482e+02 -1.20159596e+04
  1.71791788e+04  7.71659758e+03 -8.38271140e+03  3.34816848e+03
 -4.55992419e+03 -2.02225699e+04  6.55451565e+03  1.99924191e+04
 -5.08183015e+03  4.96643738e+03  1.33844179e+02  2.47957365e+04
 -1.26056490e+04 -2.24123364e+03  1.12976922e+04 -1.46603519e+03]

In [62]:
from numpy._core import numeric
print(X_test.isnull().sum())
X_test=X_test.fillna(X_train.mean(numeric_only=True))

Car ID                    250
Year                      250
Engine Size               250
Price                     250
Brand_Audi                  0
Brand_BMW                   0
Brand_Ford                  0
Brand_Honda                 0
Brand_Mercedes              0
Brand_Tesla                 0
Brand_Toyota                0
Fuel Type_Diesel            0
Fuel Type_Electric          0
Fuel Type_Hybrid            0
Fuel Type_Petrol            0
Transmission_Automatic      0
Transmission_Manual         0
Condition_Like New          0
Condition_New               0
Condition_Used              0
Model_3 Series              0
Model_5 Series              0
Model_A3                    0
Model_A4                    0
Model_Accord                0
Model_C-Class               0
Model_CR-V                  0
Model_Camry                 0
Model_Civic                 0
Model_Corolla               0
Model_E-Class               0
Model_Explorer              0
Model_Fiesta                0
Model_Fit                   0
Model_Focus                 0
Model_GLA                   0
Model_GLC                   0
Model_Model 3               0
Model_Model S               0
Model_Model X               0
Model_Model Y               0
Model_Mustang               0
Model_Prius                 0
Model_Q5                    0
Model_Q7                    0
Model_RAV4                  0
Model_X3                    0
Model_X5                    0
dtype: int64

In [63]:
Y_pred = model.predict(X_test)

print("Predicted Values:")
print(Y_pred[:10])

print("Actual Values:")
print(Y_test.head(10).values)

Predicted Values:
[149835.22775239 149835.22775239 149835.22775239 149835.22775239
 149835.22775239 149835.22775239 149835.22775239 149835.22775239
 149835.22775239 149835.22775239]
Actual Values:
[nan nan nan nan nan nan nan nan nan nan]

In [65]:
import joblib

joblib.dump(model, "LR_ford_car.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

print("Model Saved Successfully")

Model Saved Successfully