<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/pandas/blob/main/task20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
uploaded=files.upload()

Saving ford_car_dataset.csv to ford_car_dataset.csv

In [4]:
filepath="/content/ford_car_dataset.csv"
df=pd.read_csv("ford_car_dataset.csv")

In [5]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

In [19]:
print("Independent:")
x=df.drop('price',axis=1)
x.head()

Independent:

    model  year transmission  mileage fuelType  tax   mpg  engineSize
0  Fiesta  2017    Automatic    15944   Petrol  150  57.7         1.0
1   Focus  2018       Manual     9083   Petrol  150  57.7         1.0
2   Focus  2017       Manual    12456   Petrol  150  57.7         1.0
3  Fiesta  2019       Manual    10460   Petrol  145  40.3         1.5
4  Fiesta  2019    Automatic     1482   Petrol  145  48.7         1.0

In [20]:
print("Dependent:")
y=df['price']
y.head()

Dependent:

0    12000
1    14000
2    13000
3    17500
4    16500
Name: price, dtype: int64

In [21]:
print("Shape of x:",x.shape)
print("Shape of y:",y.shape)

Shape of x: (17966, 8)
Shape of y: (17966,)

In [26]:
categorical=x.select_dtypes(include=['object']).columns
print("Categorical columns:",categorical)

X_encoded = pd.get_dummies(X, columns=categorical)

X_encoded = X_encoded.astype(int)

X_encoded.head()

Categorical columns: Index(['model', 'transmission', 'fuelType'], dtype='object')

,year,mileage,tax,mpg,engineSize,model_B-MAX,model_C-MAX,model_EcoSport,model_Edge,model_Escort,...,model_Tourneo Custom,model_Transit Tourneo,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [27]:
from sklearn.preprocessing import StandardScaler

numerical_columns = ['year', 'mileage', 'tax', 'mpg', 'engineSize']

scaler = StandardScaler()

X_encoded[numerical_columns] = scaler.fit_transform(X_encoded[numerical_columns])

X_encoded.head()

,year,mileage,tax,mpg,engineSize,model_B-MAX,model_C-MAX,model_EcoSport,model_Edge,model_Escort,...,model_Tourneo Custom,model_Transit Tourneo,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0.065128,-0.380998,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0.552866,-0.733359,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,0.065128,-0.560132,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,1.040605,-0.662640,0.510727,-1.721198,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,1.040605,-1.123724,0.510727,-0.931045,-0.447984,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_encoded,Y,test_size=0.33,random_state=42)
print("X_train shape:",X_train.shape)
print("X_test shape:",X_test.shape)
print("Y_train shape:",Y_train.shape)
print("Y_test shape:",Y_test.shape)

X_train shape: (12037, 36)
X_test shape: (5929, 36)
Y_train shape: (12037,)
Y_test shape: (5929,)

In [32]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, Y_train)
print("model intercept:",model.intercept_)
print("\nmodel coefficients:",model.coef_)

model intercept: 17210.917497439557

model coefficients: [ 2.03818946e+03 -1.31848791e+03 -2.06050222e+01 -9.88971793e+02
  8.79697086e+02 -3.85258470e+03 -2.88119979e+03 -2.56429196e+03
  4.59914526e+03  1.00510970e+04 -2.92630710e+03 -8.36489160e+02
 -3.61467974e+02  1.83738861e+03 -2.61497842e+03  1.61968085e+02
 -4.29324379e+03 -6.76267978e+03 -6.25826661e+02 -1.43413077e+03
  9.16856737e+03  3.36624457e+03  0.00000000e+00  1.68117204e+03
  1.81898940e-12 -4.27251919e+02  1.69790887e+03 -2.98303973e+03
  2.52400422e+02 -2.56788946e+02  4.38852465e+00 -2.00123529e+03
  0.00000000e+00  6.64440783e+03 -1.34128580e+03 -3.30188674e+03]

In [44]:
Y_prediction=model.predict(X_test)
print("predicted value:",Y_prediction[:10])
compare=pd.DataFrame({"Actual Price": Y_test[:10],"Predicted Price": Y_pred[:10]})
print(compare)

predicted value: [ 6886.43611974  9329.53758889  9419.36269037  4494.44391177
  2429.15179332 16980.39203353 28490.75684787 12484.09019267
 11373.10359113 17275.9738973 ]
       Actual Price  Predicted Price
17610          6995      6886.436120
7076           8999      9329.537589
1713           7998      9419.362690
1611           5491      4494.443912
16830          3790      2429.151793
14735         18200     16980.392034
322           22998     28490.756848
8164          11000     12484.090193
6822           7600     11373.103591
2133          14985     17275.973897

In [46]:
from sklearn.metrics import r2_score
r2 = r2_score(Y_test, Y_pred)
print("R2 Score:", r2)

R2 Score: 0.8401958871469839

In [47]:
import joblib
joblib.dump(model, "LR_ford_car.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X_encoded.columns.tolist(), "columns.pkl")
print("Model, Scaler and Columns saved successfully!")

Model, Scaler and Columns saved successfully!